mod asset_category_code;
mod asset_category_id;
mod asset_category_name;
mod asset_id;
mod asset_inventory_status;
mod asset_name;
mod asset_parameter_code;
mod asset_parameter_data_type;
mod asset_parameter_id;
mod asset_parameter_name;
mod asset_parameter_option_label;
mod asset_tracking_mode;
mod attachment_description;
mod attachment_display_name;
mod attachment_file_name;
mod attachment_file_size;
mod attachment_id;
mod attachment_sha256;
mod attachment_storage_backend;
mod attachment_storage_key;
mod attachment_upload_id;
mod attachment_visibility;
mod laboratory_id;
mod location_code;
mod location_id;
mod location_name;
mod new_asset;
mod new_asset_category;
mod new_asset_parameter;
mod new_attachment;
mod new_location;
mod new_unit;
mod new_user;
mod phone_number;
mod unit_code;
mod unit_dimension;
mod unit_name;
mod unit_symbol;
mod update_asset;
mod update_asset_category;
mod update_asset_parameter;
mod update_attachment;
mod update_location;
mod update_unit;
mod update_user;
mod user_email;
mod user_id;
mod user_name;
mod user_password;
mod user_type;

pub use asset_category_code::*;
pub use asset_category_id::*;
pub use asset_category_name::*;
pub use asset_id::*;
pub use asset_inventory_status::*;
pub use asset_name::*;
pub use asset_parameter_code::*;
pub use asset_parameter_data_type::*;
pub use asset_parameter_id::*;
pub use asset_parameter_name::*;
pub use asset_parameter_option_label::*;
pub use asset_tracking_mode::*;
pub use attachment_description::*;
pub use attachment_display_name::*;
pub use attachment_file_name::*;
pub use attachment_file_size::*;
pub use attachment_id::*;
pub use attachment_sha256::*;
pub use attachment_storage_backend::*;
pub use attachment_storage_key::*;
pub use attachment_upload_id::*;
pub use attachment_visibility::*;
pub use laboratory_id::*;
pub use location_code::*;
pub use location_id::*;
pub use location_name::*;
pub use new_asset::*;
pub use new_asset_category::*;
pub use new_asset_parameter::*;
pub use new_attachment::*;
pub use new_location::*;
pub use new_unit::*;
pub use new_user::*;
pub use phone_number::*;
pub use unit_code::*;
pub use unit_dimension::*;
pub use unit_name::*;
pub use unit_symbol::*;
pub use update_asset::*;
pub use update_asset_category::*;
pub use update_asset_parameter::*;
pub use update_attachment::*;
pub use update_location::*;
pub use update_unit::*;
pub use update_user::*;
pub use user_email::*;
pub use user_id::*;
pub use user_name::*;
pub use user_password::*;
pub use user_type::*;
