application:
  port: 8000
  host: "0.0.0.0"
  base_url: "http://127.0.0.1:8000"
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
  cookie_secure: false
  cors_allowed_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://localhost:3000"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "lab_inventory"
  require_ssl: false
redis_uri: "redis://127.0.0.1:6379"
